In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Daily_activity.csv")

In [3]:
df.columns

Index(['Id', 'ActivityDate', 'ActivityDay', 'TotalSteps', 'TotalDistance',
       'TrackerDistance', 'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories', 'Unnamed: 16',
       'Unnamed: 17'],
      dtype='object')

In [4]:
df.dropna(axis = 1, inplace  = True )
df

,Id,ActivityDate,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 17
0,1503960366,04-12-2016,Tue,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985,Tue
1,1503960366,4/13/2016,Wed,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797,Wed
2,1503960366,4/14/2016,Thu,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776,Thu
3,1503960366,4/15/2016,Fri,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745,Fri
4,1503960366,4/16/2016,Sat,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863,Sat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,Sun,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847,Sun
936,8877689391,05-09-2016,Mon,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710,Mon
937,8877689391,05-10-2016,Tue,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832,Tue
938,8877689391,05-11-2016,Wed,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832,Wed
939,8877689391,05-12-2016,Thu,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849,Thu

In [5]:
df[df["ActivityDay"] == "Tue"]

,Id,ActivityDate,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 17
0,1503960366,04-12-2016,Tue,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985,Tue
7,1503960366,4/19/2016,Tue,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.00,50,31,264,775,2035,Tue
14,1503960366,4/26/2016,Tue,13755,8.79,8.79,0.0,2.33,0.92,5.54,0.00,31,23,279,833,1970,Tue
21,1503960366,05-03-2016,Tue,15103,9.66,9.66,0.0,3.73,1.05,4.88,0.00,50,24,254,816,1990,Tue
28,1503960366,05-10-2016,Tue,12207,7.77,7.77,0.0,3.35,1.16,3.26,0.00,46,31,214,746,1859,Tue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909,8877689391,04-12-2016,Tue,23186,20.40,20.40,0.0,12.22,0.34,7.82,0.00,85,7,312,1036,3921,Tue
916,8877689391,4/19/2016,Tue,18785,17.40,17.40,0.0,12.15,0.18,5.03,0.00,82,13,214,1131,3676,Tue
923,8877689391,4/26/2016,Tue,11101,8.43,8.43,0.0,1.76,0.13,6.50,0.00,22,3,258,1157,2860,Tue
930,8877689391,05-03-2016,Tue,10818,8.21,8.21,0.0,1.39,0.10,6.67,0.01,19,3,229,1189,2817,Tue
937,8877689391,05-10-2016,Tue,10733,8.15,8.15,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832,Tue

In [6]:
df.LoggedActivitiesDistance.value_counts()

0.000000    908
2.092147      9
2.253081      7
4.911146      1
4.081692      1
4.930550      1
4.942142      1
2.832326      1
4.869783      1
4.885605      1
3.167822      1
2.785175      1
4.924841      1
3.285415      1
4.861792      1
4.851307      1
4.878232      1
1.959596      1
4.912368      1
Name: LoggedActivitiesDistance, dtype: int64

In [7]:
id_group = df.groupby(by = "Id")
id_group.describe().transpose()

Id                  1503960366   1624580081   1644430081   1844505072  \
TotalSteps count     31.000000    31.000000    30.000000    31.000000
           mean   12116.741935  5743.903226  7282.966667  2580.064516
           std     3052.484201  6177.048612  4325.478825  2712.836854
           min        0.000000  1510.000000  1223.000000     0.000000
           25%    10573.000000  2614.500000  3603.250000     0.000000
...                        ...          ...          ...          ...
Calories   min        0.000000  1002.000000  1276.000000   665.000000
           25%     1787.000000  1381.500000  2491.000000  1347.000000
           50%     1837.000000  1435.000000  2802.500000  1549.000000
           75%     1954.000000  1525.500000  3180.000000  1803.500000
           max     2159.000000  2690.000000  3846.000000  2130.000000

Id                 1927972279    2022484408   2026352035   2320127002  \
TotalSteps count    31.000000     31.000000    31.000000    31.000000
           mean    916.129032  11370.645161  5566.870968  4716.870968
           std    1205.269064   2806.994710  2977.834815  2254.614642
           min       0.000000   3292.000000   254.000000   772.000000
           25%       0.000000  10193.000000  3412.500000  3406.500000
...                       ...           ...          ...          ...
Calories   min    1383.000000   1848.000000  1141.000000  1125.000000
           25%    2063.000000   2385.000000  1410.000000  1621.500000
           50%    2100.000000   2529.000000  1521.000000  1779.000000
           75%    2331.000000   2720.500000  1662.500000  1865.000000
           max    2638.000000   3158.000000  1926.000000  2124.000000

Id                 2347167796   2873212765  ...   6775888955   6962181067  \
TotalSteps count    18.000000    31.000000  ...    26.000000    31.000000
           mean   9519.666667  7555.774194  ...  2519.692308  9794.806452
           std    4682.093700  1514.471585  ...  3027.802540  3941.753387
           min      42.000000  2524.000000  ...     0.000000  1551.000000
           25%    6984.250000  7369.000000  ...     0.000000  6315.000000
...                       ...          ...  ...          ...          ...
Calories   min     403.000000  1431.000000  ...  1032.000000   928.000000
           25%    1944.500000  1880.000000  ...  1841.000000  1852.500000
           50%    2071.500000  1907.000000  ...  2023.000000  2039.000000
           75%    2197.000000  1993.000000  ...  2379.750000  2167.500000
           max    2670.000000  2241.000000  ...  3727.000000  2571.000000

Id                  7007744171   7086361926    8053475328   8253242879  \
TotalSteps count     26.000000    31.000000     31.000000    19.000000
           mean   11323.423077  9371.774194  14763.290323  6482.157895
           std     5306.477598  3857.093316   5440.962055  3141.325132
           min        0.000000     0.000000   1170.000000     0.000000
           25%     8067.500000  8574.500000  12443.500000  4387.000000
...                        ...          ...           ...          ...
Calories   min      120.000000  1199.000000   1505.000000     0.000000
           25%     2308.750000  2489.500000   2827.500000  1734.000000
           50%     2752.500000  2735.000000   3023.000000  1880.000000
           75%     2922.000000  2790.500000   3199.500000  1992.000000
           max     3180.000000  2997.000000   3589.000000  2218.000000

Id                 8378563200   8583815059   8792009665    8877689391
TotalSteps count    31.000000    31.000000    29.000000     31.000000
           mean   8717.709677  7198.516129  1853.724138  16040.032258
           std    3929.338521  3401.729275  2327.360214   5821.315135
           min    2132.000000     0.000000     0.000000   4790.000000
           25%    5886.500000  4763.000000     0.000000  11150.500000
...                       ...          ...          ...           ...
Calories   min    1976.000000     0.000000    57.000000   1849.000000
           25%    2945.000000  2621.500000  1688.000000   2853.500000
           50%    3635.000000  2804.000000  1934.000000   3566.000000
           75%    3787.500000  2945.500000  2067.000000   3820.000000
           max    4236.000000  3513.000000  3101.000000   4547.000000

[104 rows x 33 columns]

In [8]:
days_group = df.groupby(by = "ActivityDay").describe().transpose()
days_group.loc["Id"]

ActivityDay,Fri,Mon,Sat,Sun,Thu,Tue,Wed
count,1.260000e+02,1.200000e+02,1.240000e+02,1.210000e+02,1.470000e+02,1.520000e+02,1.500000e+02
mean,4.880997e+09,4.859930e+09,4.908075e+09,4.847640e+09,4.837277e+09,4.851063e+09,4.815191e+09
std,2.426757e+09,2.437851e+09,2.434430e+09,2.431433e+09,2.435434e+09,2.434820e+09,2.426619e+09
min,1.503960e+09,1.503960e+09,1.503960e+09,1.503960e+09,1.503960e+09,1.503960e+09,1.503960e+09
25%,2.326887e+09,2.320127e+09,2.320127e+09,2.320127e+09,2.320127e+09,2.320127e+09,2.320127e+09
50%,4.501862e+09,4.501862e+09,4.558610e+09,4.445115e+09,4.445115e+09,4.445115e+09,4.445115e+09
75%,6.962181e+09,6.962181e+09,6.973572e+09,6.962181e+09,6.962181e+09,6.962181e+09,6.962181e+09
max,8.877689e+09,8.877689e+09,8.877689e+09,8.877689e+09,8.877689e+09,8.877689e+09,8.877689e+09

In [9]:
id_group.TotalSteps.mean()

Id
1503960366    12116.741935
1624580081     5743.903226
1644430081     7282.966667
1844505072     2580.064516
1927972279      916.129032
2022484408    11370.645161
2026352035     5566.870968
2320127002     4716.870968
2347167796     9519.666667
2873212765     7555.774194
3372868164     6861.650000
3977333714    10984.566667
4020332650     2267.225806
4057192912     3838.000000
4319703577     7268.838710
4388161847    10813.935484
4445114986     4796.548387
4558609924     7685.129032
4702921684     8572.064516
5553957443     8612.580645
5577150313     8304.433333
6117666160     7046.714286
6290855005     5649.551724
6775888955     2519.692308
6962181067     9794.806452
7007744171    11323.423077
7086361926     9371.774194
8053475328    14763.290323
8253242879     6482.157895
8378563200     8717.709677
8583815059     7198.516129
8792009665     1853.724138
8877689391    16040.032258
Name: TotalSteps, dtype: float64

In [10]:
id_group.describe().loc[8877689391]

TotalSteps  count       31.000000
            mean     16040.032258
            std       5821.315135
            min       4790.000000
            25%      11150.500000
                         ...
Calories    min       1849.000000
            25%       2853.500000
            50%       3566.000000
            75%       3820.000000
            max       4547.000000
Name: 8877689391, Length: 104, dtype: float64

In [11]:
id_group.sum()

,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
Id,,,,,,,,,,,,,
1503960366,375619,242.099999,242.099999,0.000000,88.610000,24.620000,128.740000,0.00,1200,594,6818,26293,56309
1624580081,178061,121.360001,121.360001,0.000000,29.120000,11.180000,80.810000,0.19,269,180,4758,38990,45984
1644430081,218489,158.860001,158.860001,0.000000,21.900000,28.530000,108.270001,0.12,287,641,5354,34856,84339
1844505072,79982,52.890000,52.890000,0.000000,0.260000,1.520000,51.069999,0.00,4,40,3579,37405,48778
1927972279,28400,19.670000,19.670000,0.000000,2.970000,0.970000,15.720000,0.00,41,24,1196,40840,67357
2022484408,352490,250.609998,250.609998,0.000000,75.069999,22.320000,153.220000,0.00,1125,600,7981,34490,77809
2026352035,172573,107.100000,107.100000,0.000000,0.190000,0.350000,106.520000,0.00,3,8,7956,21372,47760
2320127002,146223,98.819999,98.819999,0.000000,3.310000,3.030000,92.390000,0.00,42,80,6144,37823,53449
2347167796,171354,114.400000,114.400000,0.000000,19.070000,19.350000,75.990001,0.00,243,370,4545,12369,36782
2873212765,234229,158.149999,158.149999,0.000000,20.960000,8.560000,128.450001,0.16,437,190,9548,34013,59426
3372868164,137233,94.140001,94.140001,0.000000,12.590000,3.060000,78.199999,0.22,183,82,6558,21551,38662
3977333714,329537,225.509998,225.509998,0.000000,48.449999,82.529999,94.030000,0.00,567,1838,5243,21226,45410
4020332650,70284,50.410000,50.410000,0.000000,4.410000,4.020000,40.560000,0.17,161,166,2385,38355,73960
4057192912,15352,11.450000,11.450000,0.000000,0.210000,0.260000,10.750000,0.00,3,6,412,4869,7895
4319703577,225334,151.659999,151.659999,0.000000,8.620000,15.570000,116.829999,0.00,111,382,7092,22810,63168
4388161847,335232,260.190003,260.190003,0.000000,53.300000,27.960000,167.280000,0.00,718,631,7110,25937,95910
4445114986,148693,100.620000,100.620000,0.000000,16.220000,2.340000,81.990000,0.00,205,54,6482,25727,67772
4558609924,238239,157.500000,157.500000,0.000000,17.030000,21.150000,119.280000,0.00,322,425,8834,33902,63031
4702921684,265734,215.610000,215.610000,0.000000,12.940000,40.450000,161.990002,0.00,159,807,7362,23759,91932
5553957443,266990,174.830001,174.830001,0.000000,45.390000,20.740000,108.639999,0.00,726,403,6392,20719,58146
5577150313,249133,186.399999,186.399999,0.000000,93.410000,19.740000,72.840000,0.00,2620,895,4438,22633,100789
6117666160,197308,149.580002,149.580002,0.000000,3.590000,2.350000,135.610000,0.00,44,57,8074,22296,63312
6290855005,163837,123.900000,123.900000,0.000000,2.480000,3.720000,117.410001,0.25,80,110,6596,34598,75389
6775888955,65512,47.149999,47.149999,1.959596,18.440000,9.990000,18.500000,0.00,286,385,1044,33785,55426
6962181067,303639,204.160001,202.100000,10.034689,50.110000,29.760000,124.050001,0.21,707,574,7620,20532,61443
7007744171,294409,208.399999,196.970000,55.085507,62.790000,19.200000,126.400000,0.02,807,423,7299,27439,66144
7086361926,290525,198.030000,198.030000,0.000000,86.220000,23.970000,87.380000,0.00,1320,786,4459,26364,79557
8053475328,457662,355.729997,355.729997,0.000000,263.960001,13.140000,78.550000,0.00,2640,297,4680,35588,91320
8253242879,123161,88.680001,88.680001,0.000000,42.069999,13.220000,33.340000,0.01,390,272,2221,24460,33972
8378563200,270249,214.320002,214.320002,34.600892,77.610000,16.090000,120.569999,0.00,1819,318,4839,22200,106534
8583815059,223154,174.079998,174.079998,0.000000,24.740000,31.640000,81.140000,0.00,300,688,4287,39284,84693
8792009665,53758,34.410000,34.410000,0.000000,0.720000,1.690000,32.000000,0.00,28,117,2662,30754,56907
8877689391,497241,409.599997,409.599997,0.000000,205.760000,10.470000,191.850000,0.16,2048,308,7276,34499,106028

In [12]:
df.mean()

Id                          4.855407e+09
TotalSteps                  7.637911e+03
TotalDistance               5.489702e+00
TrackerDistance             5.475351e+00
LoggedActivitiesDistance    1.081709e-01
VeryActiveDistance          1.502681e+00
ModeratelyActiveDistance    5.675426e-01
LightActiveDistance         3.340819e+00
SedentaryActiveDistance     1.606383e-03
VeryActiveMinutes           2.116489e+01
FairlyActiveMinutes         1.356489e+01
LightlyActiveMinutes        1.928128e+02
SedentaryMinutes            9.912106e+02
Calories                    2.303610e+03
dtype: float64

In [26]:
def ifzero(x):
    if x==0:
        x = 0.1081709

In [28]:
df["LoggedActivitiesDistance"].apply(ifzero)

0      None
1      None
2      None
3      None
4      None
       ...
935    None
936    None
937    None
938    None
939    None
Name: LoggedActivitiesDistance, Length: 940, dtype: object

In [29]:
df

,Id,ActivityDate,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 17
0,1503960366,04-12-2016,Tue,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985,Tue
1,1503960366,4/13/2016,Wed,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797,Wed
2,1503960366,4/14/2016,Thu,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776,Thu
3,1503960366,4/15/2016,Fri,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745,Fri
4,1503960366,4/16/2016,Sat,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863,Sat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,Sun,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847,Sun
936,8877689391,05-09-2016,Mon,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710,Mon
937,8877689391,05-10-2016,Tue,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832,Tue
938,8877689391,05-11-2016,Wed,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832,Wed
939,8877689391,05-12-2016,Thu,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849,Thu

In [36]:
df_steps = df.sort_values(by = ["Id","TotalSteps"])
df_steps

,Id,ActivityDate,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 17
30,1503960366,05-12-2016,Thu,0,0.000000,0.000000,0.0,0.00,0.00,0.00,0.0,0,0,0,1440,0,Thu
5,1503960366,4/17/2016,Sun,9705,6.480000,6.480000,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728,Sun
3,1503960366,4/15/2016,Fri,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,Fri
9,1503960366,4/21/2016,Thu,9819,6.340000,6.340000,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775,Thu
12,1503960366,4/24/2016,Sun,10039,6.410000,6.410000,0.0,2.92,0.21,3.28,0.0,39,5,238,709,1788,Sun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,8877689391,05-06-2016,Fri,21727,19.340000,19.340000,0.0,12.79,0.29,6.16,0.0,96,17,232,1095,4015,Fri
909,8877689391,04-12-2016,Tue,23186,20.400000,20.400000,0.0,12.22,0.34,7.82,0.0,85,7,312,1036,3921,Tue
924,8877689391,4/27/2016,Wed,23629,20.650000,20.650000,0.0,13.07,0.44,7.10,0.0,93,8,235,1104,3808,Wed
927,8877689391,4/30/2016,Sat,27745,26.719999,26.719999,0.0,21.66,0.08,4.93,0.0,124,4,223,1089,4398,Sat
913,8877689391,4/16/2016,Sat,29326,25.290001,25.290001,0.0,13.24,1.21,10.71,0.0,94,29,429,888,4547,Sat

In [40]:
df.LoggedActivitiesDistance.astype(int).isull()

AttributeError: 'Series' object has no attribute 'isull'